YaTube/YaTube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # импорт правил из приложения posts_back
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

YaTube/posts/urls.py
from django.urls import path
from . import views

app_name: str = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
]

YaTube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(
        unique=True,
        max_length=200
    )
    description = models.TextField()

    def __str__(self):
        return f"<Group {self.title}>"

class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )

YaTube/posts/views.py
from turtle import title
from django.shortcuts import render, get_object_or_404
from .models import Post, Group

POST_PER_PAGE  = 10
def index(request):
    posts = Post.objects.order_by('-pub_date')[:POST_PER_PAGE]
    context = {
        'title': title,
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:POST_PER_PAGE]
    context = {
        'title': title,
        'posts': posts,
        'group': group,
    }
    return render(request, 'posts/group_list.html', context)

YaTube/templates/base.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{$ static 'css/bootstrap.min.css' %}">
    <title> {% block title %}  {% endblock %} </title>
  </head>
  <body>
  {% include 'includes/header.html' %}
    <main>
      <div class="container">
      {% block content %}
      {% endblock %}
      </div>
    </main>
      {% include 'includes/footer.html' %}
  </body>
</html>

YaTube/templates/includes/footer.html
<footer class="footer-copyright text-center py-3">© 2020 Copyright
    <p><span style="color:red">Ya</span>tube</p>
</footer>

YaTube/templates/includes/header.html
{% load static %}
  <header>
    <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
    <!-- В дальнейшем тут будет создано полноценное меню -->
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30"
            class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube
        </a>
      </div>
    </nav>
  </header>

YaTube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} Лев Толстой {% endblock %}
{% block content %}
  <main>
    <!-- класс py-5 создает отступы сверху и снизу блока -->
    <div class="container py-5"> </div>
    <h1>  Лев Толстой – зеркало русской революции. </h1>
      <p>
        Группа тайных поклонников графа.
      </p>
        {% for post in posts %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            <p>
              {{ post.text }}
            </p>
          </article>
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
            {% if not forloop.last %} <hr> {% endif %}
        {% endfor %}
  </main>
{% endblock %}

YaTube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %} Последние обновления на сайте  {% endblock %}

{% block content %}
  {% for post in posts %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p> {{ post.text }}</p>
    </article>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
    {% if not forloop.last %} <hr> {% endif %}
  {% endfor %}
{% endblock %}